  SELECT DISTINCT ROW_NUMBER() OVER (ORDER BY a.MSG_NO ASC) AS ROW_NUM, a.*,d.SYSTEM_VALUE_TXT FROM TB_R_SFN_CENTRAL  a
  left join TB_M_PART b on a.MSG_NO=b.MSG_NO left join TB_H_SFN_CENTRAL_LOG c on a.MSG_NO = c.MSG_NO 
  and a.BDNO =c.ASD_VINNO LEFT JOIN TB_M_SYSTEM d on a.JUDGE =d.SYSTEM_VALUE_NUM and d.SYSTEM_TYPE ='JUDGE_CD'
  and a.MSG_NO =d.SYSTEM_CD and d.SYSTEM_CD <>'NVCS' 